### ISSUE TITLE
Migrate SQForm to TypeScript

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#244]
Perform initial TypeScript setup on this library so devs can begin to convert form components to TS over time. 

---

@codyarose edit: 
## Typescript Migration

We can start the migration process! We'll be working against this branch: `issue/244-EnableTypeScript`, and this issue will be used to track the files that need to be converted from JS to TS in a task list.

### The process will be :
- pick a component/file/folder to migrate
- create an issue to claim it
- create a branch off the remote branch `issue/244-EnableTypeScript`
- convert the file to TS
- create a PR that will merge into `issue/244-EnableTypeScript`
    - add a reference to this issue in the PR description; `Ref #244`

When everything is converted to TS, #248 will be merged to `master`

## Types can be tricky -- take your best stab at it. 
If you get stuck on something there's a good chance someone else has, or would, too, so ask for help in Slack or leave some comments on your PR about where you got stuck or what you're not sure about.

---

'folderName/`*`' means all files in that folder must be converted to Typescript as one task

- [x] src/
	- [x] `index.js`
	- [x] hooks/`*`
	- [x] #402
	- [x] components/
		- [x] #301 
		- [x] #359
		- [x] SQForm/
			- [x] #524
			- [x] #555
			- [x] #556
			- [x] #346
			- [x] #406
			- [x] #384
			- [x] `SQFormButton.js`
			- [x] #336 
			- [x] #314 
			- [x] #315 
			- [x] #335 
			- [x] #369
			- [x] #432
			- [x] #428
			- [x] #378
			- [x] #332
			- [x] #351
			- [x] #344
			- [x] #379
			- [x] #394
			- [x] #409
			- [x] #400
			- [x] #342 
			- [x] #311 
			- [x] #364
			- [x] #368 
			- [x] #366
			- [x]  #341 
			- [x] `useForm.js`
			- [x] #349
			- [x] #474
		- [x] #395
		- [x] #506
		- [x] #478
		- [x] #526
		- [x] #566
		- [x] #567
- [x] stories/
	- [x] #415
	- [x] #417
	- [x] #348
		- [x] #591
		- [x] #588
		- [x] #606
		- [x] #593
		- [x] #549
		- [x] #552
		- [x] #545
		- [x] `SQFormButton.stories.test.js`
		- [x] #408
		- [x] #539
		- [x] #427
		- [x] #422 
		- [x] #534
		- [x] #424 
		- [x] #542
		- [x] #615
	- [x] #530
	- [x] #532
	- [x] #544
	- [x] #579
	- [x] `SQFormCheckboxGroup.stories.js`
	- [x] #551
	- [x] #581
	- [x] #580
	- [x] #538
	- [x] #589
	- [x] #572
	- [x] #508
	- [x] #422
	- [x] #596
	- [x] #570
	- [x] #574
	- [x] #576
	- [x] #535
	- [x] #560
	- [x] #559
	- [x] #558
	- [x] #424
	- [x] #541
	- [x] #607
	- [x] #594
	- [x] #605
	- [x] #618
	- [x] #612
- [x] \_\_mocks\_\_/`*` #419 
- [x] `commitlint.config.js` #419 
- [x] `fileTransformer.js` #419 
- [x] `jest.config.js` #419 
- [x] `release.config.js` #419 
- [x] `rollup.config.js` #419 
- [x] #623
- [x] #626

- [x] Other
  - [x] #614 
  - [x] `Refactor to import type syntax` #494 
  - [x] #620
  - [x] #627
  - [x] #638 
  - [x] #640

**Comment by codyarose** [comment]
yeeessssss.

**Comment by SeanGroff** [comment]
Passing this beast over to @codyarose to get the draft PR over the finish line
